server:
  port: 9000
  servlet:
    context-path: /linktic/test
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linktic
    username: postgres
    password: admin
  jpa:
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
      
springdoc:
  api-docs.path : /api-docs
  swagger-ui.path : /swagger-ui.html
  swagger-ui.enabled : true